export const QUERIES_KEY = {
  AUTH: {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
  },
  USER: {
    PROFILE: "USER_PROFILE",
  },
  COURSE: {
    LIST: "COURSE_LIST",
    DETAIL: "COURSE_DETAIL",
    MY_COURSES: "MY_COURSES",
    WHISHLIST: "WISHLIST",
  },
  CART: {
    MY_CART: "MY_CART",
  },
  ORDER: {
    HISTORY: "ORDER_HISTORY",
    DETAIL: "ORDER_DETAIL",
  },
  LESSON: {
    FROM_COURSE: "LESSON_FROM_COURSE",
    DETAIL: "LESSON_DETAIL",
  },
  ENROLLMENT: {
    FROM_COURSE: "ENROLLMENT_FROM_COURSE",
    MY_ENROLLMENTS: "MY_ENROLLMENTS",
  },
  QUIZ: {
    LIST: "QUIZ_LIST",
    DETAIL: "QUIZ_DETAIL",
    QUESTIONS: "QUIZ_QUESTIONS",
    SUBMIT: "QUIZ_SUBMIT",
    ATTEMPT: "QUIZ_ATTEMPT",
    HISTORY: "QUIZ_HISTORY",
    EXPLAN_ANSWER: "QUIZ_EXPLAN_ANSWER",
  },
  CHAT_HISTORY: {
    CHAT_HISTORY: "CHAT_HISTORY",
  },
};
